#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Deploy Next.js app to VPS
#
# Run from your local machine (from the project root):
#   ./scripts/deploy.sh <VPS_IP>
#
# First deploy (--init flag applies schema + generates .env.production):
#   ./scripts/deploy.sh <VPS_IP> --init
#
# What this does:
#   1. rsync web/ to VPS
#   2. rsync scripts/ (for schema + migrations)
#   3. [--init] Generate .env.production with real secrets
#   4. [--init] Apply database schema + migrations
#   5. npm ci && npm run build
#   6. Install/configure nginx
#   7. [--init] Run certbot for SSL
#   8. PM2 restart
# =============================================================================
set -euo pipefail

# --- Config ---
VPS_USER="butter"
REMOTE_DIR="/home/butter/unsaltedbutter"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

# --- Args ---
VPS_IP="${1:-}"
INIT_MODE=false
if [[ "${2:-}" == "--init" ]]; then
    INIT_MODE=true
fi

if [[ -z "${VPS_IP}" ]]; then
    echo "Usage: ./scripts/deploy.sh <VPS_IP> [--init]"
    echo ""
    echo "  <VPS_IP>   IP address of the Hetzner VPS"
    echo "  --init     First deploy: generate .env.production, apply schema, setup SSL"
    exit 1
fi

SSH_CMD="ssh ${VPS_USER}@${VPS_IP}"

echo ""
echo "================================================"
echo "  UnsaltedButter.ai — Deploy"
echo "  Target: ${VPS_USER}@${VPS_IP}"
echo "  Mode:   $(if $INIT_MODE; then echo 'INIT (first deploy)'; else echo 'Update'; fi)"
echo "================================================"
echo ""

# Test SSH connection
${SSH_CMD} "echo 'SSH OK'" || err "Cannot SSH to ${VPS_USER}@${VPS_IP}"

# =============================================================================
# 1. rsync web app
# =============================================================================
log "Syncing web app to VPS..."
rsync -avz --delete \
    --exclude 'node_modules' \
    --exclude '.next' \
    --exclude '.env.local' \
    --exclude '.env.production' \
    "${PROJECT_ROOT}/web/" \
    "${VPS_USER}@${VPS_IP}:${REMOTE_DIR}/web/"

# =============================================================================
# 2. rsync scripts (for schema + nginx config)
# =============================================================================
log "Syncing scripts..."
rsync -avz \
    "${PROJECT_ROOT}/scripts/" \
    "${VPS_USER}@${VPS_IP}:${REMOTE_DIR}/scripts/"

# =============================================================================
# 3. [init] Generate .env.production
# =============================================================================
if $INIT_MODE; then
    log "Generating .env.production with real secrets..."

    ${SSH_CMD} bash << 'REMOTE_ENV'
set -euo pipefail

REMOTE_DIR="/home/butter/unsaltedbutter"
ENV_FILE="${REMOTE_DIR}/web/.env.production"

if [[ -f "${ENV_FILE}" ]]; then
    echo "WARNING: .env.production already exists — skipping generation"
    echo "Delete it first if you want to regenerate: rm ${ENV_FILE}"
    exit 0
fi

# Read DB password from setup-vps.sh output
DB_PASS=$(cat /home/butter/.unsaltedbutter/db_password)

# Generate secrets
JWT_SECRET=$(openssl rand -hex 32)
AGENT_API_KEY=$(openssl rand -hex 32)

cat > "${ENV_FILE}" << EOF
# Auto-generated by deploy.sh --init on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DATABASE_URL=postgresql://butter:${DB_PASS}@localhost:5432/unsaltedbutter
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY_PATH=/etc/unsaltedbutter/encryption.keyfile
BTCPAY_URL=https://pay.unsaltedbutter.ai
BTCPAY_API_KEY=CONFIGURE_AFTER_BTCPAY_SETUP
BTCPAY_STORE_ID=CONFIGURE_AFTER_BTCPAY_SETUP
BTCPAY_WEBHOOK_SECRET=CONFIGURE_AFTER_BTCPAY_SETUP
AGENT_API_KEY=${AGENT_API_KEY}
NEXT_PUBLIC_APP_URL=https://unsaltedbutter.ai
NODE_ENV=production
OPERATOR_USER_ID=
EOF

chmod 600 "${ENV_FILE}"
echo ".env.production created"
REMOTE_ENV
fi

# =============================================================================
# 4. [init] Apply database schema + migrations
# =============================================================================
if $INIT_MODE; then
    log "Applying database schema..."

    ${SSH_CMD} bash << 'REMOTE_SCHEMA'
set -euo pipefail

REMOTE_DIR="/home/butter/unsaltedbutter"
DB_PASS=$(cat /home/butter/.unsaltedbutter/db_password)
export PGPASSWORD="${DB_PASS}"

echo "Applying schema.sql..."
psql -h localhost -U butter -d unsaltedbutter -f "${REMOTE_DIR}/scripts/schema.sql"

# These migrations are for upgrading older schemas. On a fresh DB (schema.sql
# already has everything), they'll fail harmlessly on duplicate objects.
echo "Applying migrate-path-d.sql..."
psql -h localhost -U butter -d unsaltedbutter -f "${REMOTE_DIR}/scripts/migrate-path-d.sql" || echo "  (skipped — already in schema.sql)"

echo "Applying migrate-nostr-bot.sql..."
psql -h localhost -U butter -d unsaltedbutter -f "${REMOTE_DIR}/scripts/migrate-nostr-bot.sql" || echo "  (skipped — already in schema.sql)"

# This one uses IF NOT EXISTS, so it always succeeds
echo "Applying migrate-service-plans.sql..."
psql -h localhost -U butter -d unsaltedbutter -f "${REMOTE_DIR}/scripts/migrate-service-plans.sql"

echo "Schema applied successfully"
REMOTE_SCHEMA
fi

# =============================================================================
# 5. npm ci + build
# =============================================================================
log "Installing dependencies and building..."

${SSH_CMD} bash << 'REMOTE_BUILD'
set -euo pipefail

cd /home/butter/unsaltedbutter/web

echo "Running npm ci..."
npm ci

echo "Building Next.js..."
# Source .env.production for NEXT_PUBLIC_* vars, but override NODE_ENV
# so npm ci (above) doesn't skip dev dependencies
if [[ -f .env.production ]]; then
    set -a
    source .env.production
    set +a
fi
npm run build

echo "Build complete"
REMOTE_BUILD

# =============================================================================
# 6. nginx setup
# =============================================================================
log "Configuring nginx..."

${SSH_CMD} bash << 'REMOTE_NGINX'
set -euo pipefail

REMOTE_DIR="/home/butter/unsaltedbutter"
NGINX_CONF="/etc/nginx/sites-available/unsaltedbutter"

# Only install nginx config on first deploy (--init) or if certbot hasn't
# touched it yet. Certbot adds "managed by Certbot" comments — if those
# exist, the config has SSL blocks we don't want to overwrite.
if [[ -f "${NGINX_CONF}" ]] && grep -q "managed by Certbot" "${NGINX_CONF}"; then
    echo "nginx config has SSL (certbot) — skipping overwrite"
else
    sudo cp "${REMOTE_DIR}/scripts/nginx/unsaltedbutter.conf" "${NGINX_CONF}"
    sudo ln -sf "${NGINX_CONF}" /etc/nginx/sites-enabled/unsaltedbutter
    sudo rm -f /etc/nginx/sites-enabled/default
    echo "nginx config installed"
fi

# Test and reload
sudo nginx -t
sudo systemctl reload nginx

echo "nginx configured"
REMOTE_NGINX

# =============================================================================
# 7. [init] SSL with certbot
# =============================================================================
if $INIT_MODE; then
    log "Setting up SSL certificates..."
    warn "Certbot will prompt you for email + agreement. Answer the prompts."

    ${SSH_CMD} -t bash << 'REMOTE_SSL'
sudo certbot --nginx -d unsaltedbutter.ai -d pay.unsaltedbutter.ai
REMOTE_SSL

    log "SSL configured"
fi

# =============================================================================
# 8. PM2 start/restart
# =============================================================================
log "Starting app with PM2..."

${SSH_CMD} bash << 'REMOTE_PM2'
set -euo pipefail

cd /home/butter/unsaltedbutter/web

# Stop existing if running
pm2 delete unsaltedbutter 2>/dev/null || true

# Start with ecosystem config
pm2 start ecosystem.config.cjs

# Save PM2 process list for auto-restart on reboot
pm2 save

echo "PM2 started"
REMOTE_PM2

# =============================================================================
# 9. Verify
# =============================================================================
log "Verifying deployment..."
sleep 8

${SSH_CMD} bash << 'REMOTE_VERIFY'
set -euo pipefail

echo "=== PM2 Status ==="
pm2 list

echo ""
echo "=== Port Check ==="
if ss -tlnp | grep -q ":3000"; then
    echo "Next.js listening on :3000 ✓"
else
    echo "WARNING: Next.js not listening on :3000"
fi

echo ""
echo "=== nginx Status ==="
sudo systemctl is-active nginx && echo "nginx is running ✓"
REMOTE_VERIFY

echo ""
echo "================================================"
echo "  Deploy Complete"
echo "================================================"
echo ""
echo "  App:     https://unsaltedbutter.ai"
echo "  BTCPay:  https://pay.unsaltedbutter.ai"
echo ""
if $INIT_MODE; then
    echo "  NEXT STEPS:"
    echo "  1. Visit https://unsaltedbutter.ai — verify it loads"
    echo "  2. Wait for Bitcoin sync to complete"
    echo "  3. Visit https://pay.unsaltedbutter.ai → create admin account"
    echo "  4. Create store, generate API key, set webhook"
    echo "  5. Update .env.production with BTCPay credentials:"
    echo "     ssh ${VPS_USER}@${VPS_IP} nano ${REMOTE_DIR}/web/.env.production"
    echo "  6. Restart: ssh ${VPS_USER}@${VPS_IP} 'pm2 restart unsaltedbutter'"
    echo ""
fi
